export { default as Home } from './Home'
export { default as About } from './About'
export { default as Products } from './Products'
export { default as Cart } from './Cart'
export { default as Checkout } from './Checkout'
export { default as Orders } from './Orders'
export { default as Login } from './Login'
export { default as Register } from './Register'
